### ISSUE TITLE
Top Page Layout

### ISSUE THREAD

**Issue by pmcmahon02** [WEB290-2015/webdevcapstone#14]
# Review site and and make revisions to all pages of site that are lacking the Top Page wireframe that has been agreed upon.

**Comment by jccc-dn** [comment]
I have made the top section of all pages consistent in terms of the nav, the top level headings, the page titles, and the breadcrumbs. Specifically, I have updated the navigation on all pages including all top level pages and the individual student showcase pages. I also moved the individual student showcase pages into a folder called 'showcase' and fixed all the links that were affected by this site structure change on the individual pages. I tested all pages for proper navigation behavior. I also cleaned up several problems with the minor problems like problems with the wrong image or wrong page name in the individual student showcase pages. 

One thing to be careful of is to match carefully the capitalization of all file names (image or other files) because the web server is less forgiving than your desktop machine. For example the image file 'Mockup.png' requires the precise reference 'src="../img/Mockup.png"' to load properly from the web server, but will run properly on a local Windows machine if the reference is 'src="../img/mockup.png"' since the path is not case sensitive when running locally.

PLEASE download the new corrected pages before doing any more work on them.
